/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frontend;

import backend.bag.Bag;
import backend.db.DBHelper;
import backend.result.Result;
import backend.user.Users;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lalabinaqib
 */
public class Fight extends javax.swing.JFrame {

    /**
     * Creates new form Fight
     */
    public Fight() {
        initComponents();
        showComboBoxAttacker();
        showComboBoxDefender();
        showDataResult();
        emptyForm();
    }

    public void showComboBoxAttacker() {
        String sql = "select * from user";
        try {
            ResultSet rs = DBHelper.selectQuery(sql);
            while (rs.next()) {
                comboAttaker.addItem(rs.getString("idUser"));
            }
        } catch (Exception e) {
        }

    }
    
    public void showDataResult(){
        String[] columnData = {"ID Defender", "Username","Hero","HP"};
        ArrayList<Result> listDefender = new Result().resultFight();
        Object rowData[] = new Object[4];
        
        fightTable.setModel(new DefaultTableModel(new Object[][] {}, columnData));
        
        for(Result result : listDefender){
            rowData[0] = result.getUser().getIdUser();
            rowData[1] = result.getUser().getUsername();
            rowData[2] = result.getHero().getHeroName();
            rowData[3] = result.getHero().getHp();
            ((DefaultTableModel)fightTable.getModel()).addRow(rowData);
        }
    }

    public void showComboBoxDefender() {
        String sql = "select * from user";
        try {
            ResultSet rs = DBHelper.selectQuery(sql);
            while (rs.next()) {
                comboDefence.addItem(rs.getString("idUser"));
            }
        } catch (Exception e) {
        }
    }

    public void showComboPotion() {
        String sql = "SELECT p1.idPotion ip1, p1.potionName pot1, p2.idPotion ip2, p2.potionName pot2, p3.idPotion ip3,p3.potionName pot3 "
                + "from user u\n"
                + "inner join bag b on u.idBag = b.idBag\n"
                + "inner join potion p1 on b.potion1 = p1.idPotion\n"
                + "inner join potion p2 on b.potion2 = p2.idPotion\n"
                + "inner join potion p3 on b.potion3 = p3.idPotion\n"
                + "where u.idUser = '" + comboAttaker.getSelectedItem() + "'";
        try {
            ResultSet rs = DBHelper.selectQuery(sql);
            while (rs.next()) {
                comboPotion.addItem(rs.getString("pot1"));
                comboPotion.addItem(rs.getString("pot2"));
                comboPotion.addItem(rs.getString("pot3"));
            }
        } catch (Exception e) {
        }
    }

    public void showAttacker() {
        String sql = "select u.username username, h.idHero idHero, h.heroName hero, h.role role, "
                + "h.hp hp, h.atk atk, h.spd spd, h.dfc dfc from user u "
                + "inner join hero h on u.idHero = h.idHero "
                + "where u.idUser = '" + comboAttaker.getSelectedItem() + "'";
        try {
            ResultSet rs = DBHelper.selectQuery(sql);
            while (rs.next()) {
                txtAUsername.setText(rs.getString("username"));
                txtAIdHero.setText(rs.getString("idHero"));
                txtAHeroName.setText(rs.getString("hero"));
                txtARole.setText(rs.getString("role"));
                txtAHp.setText(rs.getString("hp"));
                txtAAttack.setText(rs.getString("atk"));
                txtASpeed.setText(rs.getString("spd"));
                txtADeffend.setText(rs.getString("dfc"));
            }
        } catch (Exception e) {
        }
    }

    public void emptyForm() {
        comboAttaker.setSelectedIndex(0);
        txtAUsername.setText("0");
        txtAHeroName.setText("");
        txtARole.setText("");
        txtAHp.setText("");
        txtAAttack.setText("");
        txtASpeed.setText("");
        txtADeffend.setText("");

        comboDefence.setSelectedIndex(0);
        txtDUsername.setText("0");
        txtDHeroname.setText("");
        txtDRole.setText("");
        txtDHp.setText("");
        txtDAttack.setText("");
        txtDSpeed.setText("");
        txtDDeffend.setText("");

        comboPotion.setSelectedIndex(0);
        txtDesc.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAHeroName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtARole = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtASpeed = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtAAttack = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtAHp = new javax.swing.JTextField();
        txtADeffend = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        comboPotion = new javax.swing.JComboBox<>();
        txtDesc = new javax.swing.JTextField();
        btnExecute = new javax.swing.JButton();
        txtDSpeed = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDAttack = new javax.swing.JTextField();
        txtDRole = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtDHp = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtDHeroname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        btnAttack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        fightTable = new javax.swing.JTable();
        comboAttaker = new javax.swing.JComboBox<>();
        comboDefence = new javax.swing.JComboBox<>();
        txtDDeffend = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtAUsername = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtDUsername = new javax.swing.JTextField();
        clearBtn = new javax.swing.JButton();
        txtSkill = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtAIdHero = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        txtDIdHero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(39, 62, 108));

        jLabel1.setText("Hero");

        txtAHeroName.setEnabled(false);
        txtAHeroName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAHeroNameActionPerformed(evt);
            }
        });

        jLabel2.setText("id Attacker");

        jLabel3.setText("Role");

        txtARole.setEnabled(false);
        txtARole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtARoleActionPerformed(evt);
            }
        });

        jLabel4.setText("Speed");

        txtASpeed.setEnabled(false);
        txtASpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtASpeedActionPerformed(evt);
            }
        });

        jLabel5.setText("Attack");

        txtAAttack.setEnabled(false);
        txtAAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAAttackActionPerformed(evt);
            }
        });

        jLabel6.setText("Hp");

        txtAHp.setEnabled(false);
        txtAHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAHpActionPerformed(evt);
            }
        });

        txtADeffend.setEnabled(false);
        txtADeffend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtADeffendActionPerformed(evt);
            }
        });

        jLabel7.setText("Defence");

        jSeparator1.setEnabled(false);

        comboPotion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPotionActionPerformed(evt);
            }
        });

        txtDesc.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        txtDesc.setEnabled(false);
        txtDesc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescActionPerformed(evt);
            }
        });

        btnExecute.setText("Execute");
        btnExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExecuteActionPerformed(evt);
            }
        });

        txtDSpeed.setEnabled(false);
        txtDSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDSpeedActionPerformed(evt);
            }
        });

        jLabel8.setText("Attack");

        jLabel9.setText("Role");

        txtDAttack.setEnabled(false);
        txtDAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDAttackActionPerformed(evt);
            }
        });

        txtDRole.setEnabled(false);
        txtDRole.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDRoleActionPerformed(evt);
            }
        });

        jLabel10.setText("Hp");

        txtDHp.setEnabled(false);
        txtDHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDHpActionPerformed(evt);
            }
        });

        jLabel11.setText("Speed");

        jLabel12.setText("Hero");

        txtDHeroname.setEnabled(false);
        txtDHeroname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDHeronameActionPerformed(evt);
            }
        });

        jLabel13.setText("id Defender");

        btnAttack.setText("Attack");
        btnAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttackActionPerformed(evt);
            }
        });

        fightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(fightTable);

        comboAttaker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAttakerActionPerformed(evt);
            }
        });

        comboDefence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboDefenceActionPerformed(evt);
            }
        });

        txtDDeffend.setEnabled(false);
        txtDDeffend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDDeffendActionPerformed(evt);
            }
        });

        jLabel15.setText("Defence");

        jLabel14.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel14.setText("Potion");

        jLabel16.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel16.setText("Defence");

        jLabel17.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel17.setText("Result");

        jLabel18.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel18.setText("Attacker");

        jLabel19.setText("Username");

        txtAUsername.setEnabled(false);
        txtAUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAUsernameActionPerformed(evt);
            }
        });

        jLabel20.setText("Username");

        txtDUsername.setEnabled(false);
        txtDUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDUsernameActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        txtSkill.setEnabled(false);
        txtSkill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSkillActionPerformed(evt);
            }
        });

        jLabel21.setText("Skill");

        jLabel22.setText("idHero");

        txtAIdHero.setEnabled(false);
        txtAIdHero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAIdHeroActionPerformed(evt);
            }
        });

        jLabel23.setText("idHero");

        txtDIdHero.setEnabled(false);
        txtDIdHero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDIdHeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel19)
                            .addComponent(jLabel22))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAIdHero)
                            .addComponent(txtARole)
                            .addComponent(comboAttaker, 0, 128, Short.MAX_VALUE)
                            .addComponent(txtAUsername, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAHeroName))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtADeffend, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel4))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtASpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAHp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnExecute, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtDesc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel14)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(comboPotion, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtSkill, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel17)
                        .addGap(402, 402, 402))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9)
                            .addComponent(jLabel20)
                            .addComponent(jLabel23))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDRole, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(txtDHeroname, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(comboDefence, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDUsername)
                            .addComponent(txtDIdHero))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addGap(33, 33, 33))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDHp, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDDeffend, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAttack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(24, 24, 24)
                                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(33, 33, 33)
                    .addComponent(jLabel18)
                    .addContainerGap(920, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboPotion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSkill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))
                        .addGap(18, 18, 18)
                        .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtAHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addComponent(jLabel2)
                            .addComponent(comboAttaker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtAUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(txtASpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtAIdHero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtADeffend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(txtAHeroName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtARole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))))))
                .addGap(18, 18, 18)
                .addComponent(btnExecute)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAttack)
                            .addComponent(clearBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel20)
                                    .addComponent(txtDUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel13)
                                    .addComponent(comboDefence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDIdHero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDHeroname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtDRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10))
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDAttack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8))
                            .addGap(12, 12, 12)
                            .addComponent(txtDSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(45, 45, 45))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtDDeffend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15)))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jLabel18)
                    .addContainerGap(599, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAHeroNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAHeroNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAHeroNameActionPerformed

    private void txtARoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtARoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtARoleActionPerformed

    private void txtASpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtASpeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtASpeedActionPerformed

    private void txtAAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAAttackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAAttackActionPerformed

    private void txtAHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAHpActionPerformed

    private void txtADeffendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtADeffendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtADeffendActionPerformed

    private void txtDescActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescActionPerformed

    private void txtDSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDSpeedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDSpeedActionPerformed

    private void txtDAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDAttackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDAttackActionPerformed

    private void txtDRoleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDRoleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDRoleActionPerformed

    private void txtDHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDHpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDHpActionPerformed

    private void txtDHeronameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDHeronameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDHeronameActionPerformed

    private void btnAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttackActionPerformed
        Result result = new Result();
        result.setIdResult(Integer.parseInt((String) comboDefence.getSelectedItem()));
        result.getUser().setIdUser(Integer.parseInt((String) comboDefence.getSelectedItem()));
        result.getHero().setIdHero(Integer.parseInt((String) txtDIdHero.getText()));
        float temp = Float.parseFloat(txtDHp.getText()) - (Float.parseFloat(txtAAttack.getText()) - (Float.parseFloat(txtAAttack.getText()) * Float.parseFloat(txtDDeffend.getText()) / 100));
        String sql = "update hero set hp = '"+temp+"' where idHero = '"+txtDIdHero.getText()+"'";
        DBHelper.executeQuery(sql);
        result.saveResult();
        comboDefence.setSelectedItem(Integer.toString(result.getIdResult()));
        showDataResult();
    }//GEN-LAST:event_btnAttackActionPerformed

    private void txtDDeffendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDDeffendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDDeffendActionPerformed

    private void btnExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExecuteActionPerformed
        if (Integer.parseInt(txtSkill.getText()) == 10) {
            float temp = Float.parseFloat(txtAAttack.getText()) + (Float.parseFloat(txtAAttack.getText())*(Float.parseFloat(txtSkill.getText()) / 100));
            String sql = "update hero set atk = '"+temp+"' where idHero = '"+txtAIdHero.getText()+"'";
            DBHelper.executeQuery(sql);
            showAttacker();
            System.out.println("rage jalan");
            System.out.println(sql);
        }
        else if (Integer.parseInt(txtSkill.getText()) == 20) {
            float temp = Float.parseFloat(txtASpeed.getText()) + (Float.parseFloat(txtASpeed.getText())*(Float.parseFloat(txtSkill.getText()) / 100));
            String sql = "update hero set spd = '"+temp+"' where idHero = '"+txtAIdHero.getText()+"'";
            DBHelper.executeQuery(sql);
            showAttacker();
            System.out.println("turbo jalan");
            System.out.println(sql);
        }
        else if (Integer.parseInt(txtSkill.getText()) == 15) {
            float temp = Float.parseFloat(txtADeffend.getText()) + (Float.parseFloat(txtADeffend.getText())*(Float.parseFloat(txtSkill.getText()) / 100));
            String sql = "update hero set dfc = '"+temp+"' where idHero = '"+txtAIdHero.getText()+"'";
            DBHelper.executeQuery(sql);
            showAttacker();
            System.out.println("barier jalan");
            System.out.println(sql);
        }
    }//GEN-LAST:event_btnExecuteActionPerformed

    private void txtAUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAUsernameActionPerformed

    private void txtDUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDUsernameActionPerformed

    }//GEN-LAST:event_txtDUsernameActionPerformed

    private void comboAttakerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAttakerActionPerformed
        comboPotion.removeAllItems();
        showComboPotion();
        showAttacker();
    }//GEN-LAST:event_comboAttakerActionPerformed

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        // TODO add your handling code here:
        emptyForm();
    }//GEN-LAST:event_clearBtnActionPerformed

    private void comboPotionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPotionActionPerformed
        String sql = "select * from potion where potionName = '" + comboPotion.getSelectedItem() + "'";
        try {
            ResultSet rs = DBHelper.selectQuery(sql);
            while (rs.next()) {
                txtSkill.setText(rs.getString("skill"));
                txtDesc.setText(rs.getString("desc"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_comboPotionActionPerformed

    private void txtSkillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSkillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSkillActionPerformed

    private void comboDefenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboDefenceActionPerformed
        String sql = "select u.username username, h.idHero idHero, h.heroName hero, h.role role, "
                + "h.hp hp, h.atk atk, h.spd spd, h.dfc dfc from user u "
                + "inner join hero h on u.idHero = h.idHero "
                + "where u.idUser = '" + comboDefence.getSelectedItem() + "'";
        try {
            ResultSet rs = DBHelper.selectQuery(sql);
            while (rs.next()) {
                txtDUsername.setText(rs.getString("username"));
                txtDIdHero.setText(rs.getString("idHero"));
                txtDHeroname.setText(rs.getString("hero"));
                txtDRole.setText(rs.getString("role"));
                txtDHp.setText(rs.getString("hp"));
                txtDAttack.setText(rs.getString("atk"));
                txtDSpeed.setText(rs.getString("spd"));
                txtDDeffend.setText(rs.getString("dfc"));
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_comboDefenceActionPerformed

    private void txtAIdHeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAIdHeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAIdHeroActionPerformed

    private void txtDIdHeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDIdHeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDIdHeroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fight.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fight().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttack;
    private javax.swing.JButton btnExecute;
    private javax.swing.JButton clearBtn;
    private javax.swing.JComboBox<String> comboAttaker;
    private javax.swing.JComboBox<String> comboDefence;
    private javax.swing.JComboBox<String> comboPotion;
    private javax.swing.JTable fightTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtAAttack;
    private javax.swing.JTextField txtADeffend;
    private javax.swing.JTextField txtAHeroName;
    private javax.swing.JTextField txtAHp;
    private javax.swing.JTextField txtAIdHero;
    private javax.swing.JTextField txtARole;
    private javax.swing.JTextField txtASpeed;
    private javax.swing.JTextField txtAUsername;
    private javax.swing.JTextField txtDAttack;
    private javax.swing.JTextField txtDDeffend;
    private javax.swing.JTextField txtDHeroname;
    private javax.swing.JTextField txtDHp;
    private javax.swing.JTextField txtDIdHero;
    private javax.swing.JTextField txtDRole;
    private javax.swing.JTextField txtDSpeed;
    private javax.swing.JTextField txtDUsername;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtSkill;
    // End of variables declaration//GEN-END:variables
}
